# Generated by Django 3.2.12 on 2023-01-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
