# Generated by Django 3.2.12 on 2023-01-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_username_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
