# Generated by Django 3.2.12 on 2023-01-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20230112_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identification',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=21),
        ),
    ]
