# Generated by Django 3.2.12 on 2023-01-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
