# Generated by Django 3.2.12 on 2023-01-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_hided',
            field=models.BooleanField(default=False),
        ),
    ]
